/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedBrandsNewRouteImport } from './routes/_authenticated/brands.new'
import { Route as AuthenticatedBrandsBrandIdRouteImport } from './routes/_authenticated/brands.$brandId'
import { Route as ApiPublicRenderHealthRouteImport } from './routes/api/public/render/health'
import { Route as ApiPublicRenderCallbackRouteImport } from './routes/api/public/render/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsNewRoute = AuthenticatedBrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsBrandIdRoute =
  AuthenticatedBrandsBrandIdRouteImport.update({
    id: '/brands/$brandId',
    path: '/brands/$brandId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicRenderHealthRoute = ApiPublicRenderHealthRouteImport.update({
  id: '/api/public/render/health',
  path: '/api/public/render/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderCallbackRoute = ApiPublicRenderCallbackRouteImport.update({
  id: '/api/public/render/callback',
  path: '/api/public/render/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/brands/new': typeof AuthenticatedBrandsNewRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/health': typeof ApiPublicRenderHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/brands/new': typeof AuthenticatedBrandsNewRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/health': typeof ApiPublicRenderHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/brands/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/_authenticated/brands/new': typeof AuthenticatedBrandsNewRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/health': typeof ApiPublicRenderHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/brands/$brandId'
    | '/brands/new'
    | '/api/public/render/callback'
    | '/api/public/render/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/brands/$brandId'
    | '/brands/new'
    | '/api/public/render/callback'
    | '/api/public/render/health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/brands/$brandId'
    | '/_authenticated/brands/new'
    | '/api/public/render/callback'
    | '/api/public/render/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRenderCallbackRoute: typeof ApiPublicRenderCallbackRoute
  ApiPublicRenderHealthRoute: typeof ApiPublicRenderHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/new': {
      id: '/_authenticated/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof AuthenticatedBrandsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/$brandId': {
      id: '/_authenticated/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/render/health': {
      id: '/api/public/render/health'
      path: '/api/public/render/health'
      fullPath: '/api/public/render/health'
      preLoaderRoute: typeof ApiPublicRenderHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render/callback': {
      id: '/api/public/render/callback'
      path: '/api/public/render/callback'
      fullPath: '/api/public/render/callback'
      preLoaderRoute: typeof ApiPublicRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedBrandsBrandIdRoute: typeof AuthenticatedBrandsBrandIdRoute
  AuthenticatedBrandsNewRoute: typeof AuthenticatedBrandsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedBrandsBrandIdRoute: AuthenticatedBrandsBrandIdRoute,
  AuthenticatedBrandsNewRoute: AuthenticatedBrandsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRenderCallbackRoute: ApiPublicRenderCallbackRoute,
  ApiPublicRenderHealthRoute: ApiPublicRenderHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
