/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as ApiPublicRenderHealthRouteImport } from './routes/api/public/render/health'
import { Route as ApiPublicRenderCallbackRouteImport } from './routes/api/public/render/callback'
import { Route as AuthenticatedAppBrandsNewRouteImport } from './routes/_authenticated/app.brands.new'
import { Route as AuthenticatedAppBrandsBrandIdRouteImport } from './routes/_authenticated/app.brands.$brandId'
import { Route as AuthenticatedAppBrandsBrandIdReactionsRouteImport } from './routes/_authenticated/app.brands.$brandId_.reactions'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicRenderHealthRoute = ApiPublicRenderHealthRouteImport.update({
  id: '/api/public/render/health',
  path: '/api/public/render/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderCallbackRoute = ApiPublicRenderCallbackRouteImport.update({
  id: '/api/public/render/callback',
  path: '/api/public/render/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppBrandsNewRoute =
  AuthenticatedAppBrandsNewRouteImport.update({
    id: '/brands/new',
    path: '/brands/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBrandsBrandIdRoute =
  AuthenticatedAppBrandsBrandIdRouteImport.update({
    id: '/brands/$brandId',
    path: '/brands/$brandId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBrandsBrandIdReactionsRoute =
  AuthenticatedAppBrandsBrandIdReactionsRouteImport.update({
    id: '/brands/$brandId_/reactions',
    path: '/brands/$brandId/reactions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/brands/$brandId': typeof AuthenticatedAppBrandsBrandIdRoute
  '/app/brands/new': typeof AuthenticatedAppBrandsNewRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/health': typeof ApiPublicRenderHealthRoute
  '/app/brands/$brandId/reactions': typeof AuthenticatedAppBrandsBrandIdReactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/brands/$brandId': typeof AuthenticatedAppBrandsBrandIdRoute
  '/app/brands/new': typeof AuthenticatedAppBrandsNewRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/health': typeof ApiPublicRenderHealthRoute
  '/app/brands/$brandId/reactions': typeof AuthenticatedAppBrandsBrandIdReactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/brands/$brandId': typeof AuthenticatedAppBrandsBrandIdRoute
  '/_authenticated/app/brands/new': typeof AuthenticatedAppBrandsNewRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/health': typeof ApiPublicRenderHealthRoute
  '/_authenticated/app/brands/$brandId_/reactions': typeof AuthenticatedAppBrandsBrandIdReactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/account'
    | '/app/'
    | '/app/brands/$brandId'
    | '/app/brands/new'
    | '/api/public/render/callback'
    | '/api/public/render/health'
    | '/app/brands/$brandId/reactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/account'
    | '/app'
    | '/app/brands/$brandId'
    | '/app/brands/new'
    | '/api/public/render/callback'
    | '/api/public/render/health'
    | '/app/brands/$brandId/reactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/account'
    | '/_authenticated/app/'
    | '/_authenticated/app/brands/$brandId'
    | '/_authenticated/app/brands/new'
    | '/api/public/render/callback'
    | '/api/public/render/health'
    | '/_authenticated/app/brands/$brandId_/reactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicRenderCallbackRoute: typeof ApiPublicRenderCallbackRoute
  ApiPublicRenderHealthRoute: typeof ApiPublicRenderHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/render/health': {
      id: '/api/public/render/health'
      path: '/api/public/render/health'
      fullPath: '/api/public/render/health'
      preLoaderRoute: typeof ApiPublicRenderHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render/callback': {
      id: '/api/public/render/callback'
      path: '/api/public/render/callback'
      fullPath: '/api/public/render/callback'
      preLoaderRoute: typeof ApiPublicRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/brands/new': {
      id: '/_authenticated/app/brands/new'
      path: '/brands/new'
      fullPath: '/app/brands/new'
      preLoaderRoute: typeof AuthenticatedAppBrandsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brands/$brandId': {
      id: '/_authenticated/app/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/app/brands/$brandId'
      preLoaderRoute: typeof AuthenticatedAppBrandsBrandIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brands/$brandId_/reactions': {
      id: '/_authenticated/app/brands/$brandId_/reactions'
      path: '/brands/$brandId/reactions'
      fullPath: '/app/brands/$brandId/reactions'
      preLoaderRoute: typeof AuthenticatedAppBrandsBrandIdReactionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBrandsBrandIdRoute: typeof AuthenticatedAppBrandsBrandIdRoute
  AuthenticatedAppBrandsNewRoute: typeof AuthenticatedAppBrandsNewRoute
  AuthenticatedAppBrandsBrandIdReactionsRoute: typeof AuthenticatedAppBrandsBrandIdReactionsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBrandsBrandIdRoute: AuthenticatedAppBrandsBrandIdRoute,
  AuthenticatedAppBrandsNewRoute: AuthenticatedAppBrandsNewRoute,
  AuthenticatedAppBrandsBrandIdReactionsRoute:
    AuthenticatedAppBrandsBrandIdReactionsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicRenderCallbackRoute: ApiPublicRenderCallbackRoute,
  ApiPublicRenderHealthRoute: ApiPublicRenderHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
